### ISSUE TITLE
Is it possible to retain a model of the voice conversion?

### ISSUE THREAD

**Issue by HiroshiKawata** [mazzzystar/randomCNN-voice-transfer#11]
Hello, @mazzzystar !

First of all, thank you for this implementation and providing the source code. It is not an issue at all, but an assumption if it is possible to save a model after the conversion and retain it to reuse on the same source and target voice (with different samples).

**Comment by mazzzystar** [comment]
@HiroshiKawata 
Current model actually don't learn anything because it's initialized totally randomly.  
The training process is to repeatly optimize the source sound piece so that it's network output features meet our requirements, therefore the model parameter won't be updated. So there is not use to save model parameters.

However, your question reminds me of a recently paper(github [implementation](https://github.com/sunshineatnoon/LinearStyleTransfer)) which shows that image style transfer task can be learned by a linear model.  So maybe it's reasonable to train a model like that.

**Comment by HiroshiKawata** [comment]
I see. Thanks for the explanation and the paper, @mazzzystar ! 😃
